### ISSUE TITLE
buffer_cache_hit should be a percentage but is not.

### ISSUE THREAD

**Issue by riklempens** [infrasonar/mssql-probe#5]
> The buffer cache hit ratio counter represents how often SQL Server is able
> to find data pages in its buffer cache when a query needs a data page.
> 
> The higher this number the better, because it means SQL Server was able to
> get data for queries out of memory instead of reading from disk.
> 
> You want this number to be as close to 100 as possible. Having this counter
> at 100 means that 100% of the time SQL Server has found the needed data
> pages in memory.
> 
> A low buffer cache hit ratio could indicate a memory problem.

When I read the above the two metrics below should be a percentage but this does not seem to be the case:

### buffer_cache_hit_ratio_base
- Collector(10374); // mssql
- Check(10636); // instanceperfcounters
- Type(10637); // instanceperf
- Metric(10665); // buffer_cache_hit_ratio_base

### buffer_cache_hit  
- Collector(10374); // mssql
- Check(10636); // instanceperfcounters
- Type(10637); // instanceperf
- Metric(10672); // buffer_cache_hit

**Comment by Koos85** [comment]
The value should be divided by it's `_base_` value. Find out which other metrics have this problem like `average_wait_time`.

**Comment by joente** [comment]
Solved in https://github.com/infrasonar/mssql-probe/releases/tag/v3.0.5
